### ISSUE TITLE
Narrar cómo mostrar el navegador a pantalla completa

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#174]
Describir el proceso seguido en el vídeo de la tarea #159

**Comment by juannma1245** [comment]
Aquí tienes el [audio](https://drive.google.com/file/d/0B4rXBJ9q940bOUcyQU8xM201YTJZajE0b2JjSFN4d0dqVVZn/view?usp=sharing)

**Comment by profeIAP** [comment]
Juanma me ha encantado (eres el primero y, si me apuras, el único) que saluda al comenzar la grabación ¡fantástico! (que se note lo bien educado que estás, di que sí)

Llama la atención la gran cantidad de ruido de fondo que hay en la grabación ¿?

Otra cosa: no narres hasta que no obtengas el "ok" definitivo de la tarea de grabación asociada pues no quiero que hagas trabajo innecesariamente 👍

**Comment by juannma1245** [comment]
Gracias!! El lunes lo corrigo todo. Salu2 XD

El 27/1/2017 18:53, "Profesor IAP" <notifications@github.com> escribió:

Juanma me ha encantado (eres el primero y, si me apuras, el único) que
saluda al comenzar la grabación ¡fantástico! (que se note lo bien educado
que estás, di que sí)

Llama la atención la gran cantidad de ruido de fondo que hay en la
grabación ¿?

Otra cosa: no narres hasta que no obtengas el "ok" definitivo de la tarea
de grabación asociada pues no quiero que hagas trabajo innecesariamente 👍

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/profeIAP/Documentacion/issues/174#issuecomment-275727472>,
or mute the thread

**Comment by profeIAP** [comment]
Si te acuerdas, **estaría bien** que indicases en la narración que se puede poner en pantalla completa usando tanto la opción sobre la que haces click como pulsando la tecla F11 (esto haría que estuviese aún mejor el vídeo final)

**Comment by juannma1245** [comment]
[Aquí tienes de nuevo el audio](https://drive.google.com/open?id=0B4rXBJ9q940bQXM4RnMtNmNMZDZfUlVNTEdqaW43d1dtX1VB)

**Comment by profeIAP** [comment]
Te ha quedado genial e ibas muy tranquilo narrando las acciones a realizar, enhorabuena JuanMa.
Cuadrar vídeo y audio igual cuesta un poco pero, como te has asignado la tarea a ti mismo dejaré que lo intentes para ver cómo te sale 😏

**Comment by juannma1245** [comment]
Gracias!!
