### ISSUE TITLE
Grabar cómo añadir una imagen en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#48]
Crear un vídeo en el que se muestre cómo se añaden imágenes en los comentarios de GitHub.

Existen tres modos de hacerlo:
1. Arrastrando la imagen
1. Usando la opción seleccionar imagen
1. Utilizando la sintaxis de MarkDown

**Comment by noeliagmez3** [comment]
![atardecer-568470fbef6d4](https://cloud.githubusercontent.com/assets/24393386/21217317/e5bcfe94-c2ab-11e6-953d-73b9f0085423.jpg)
![atardecer-568470fbef6d4](https://cloud.githubusercontent.com/assets/24393386/21217321/eb441870-c2ab-11e6-850b-248abdfde856.jpg)
http://puzzles.tuspuzzles.es/images/original/atardecer-568470fbef6d4.jpg

**Comment by profeIAP** [comment]
La foto es muy bonita Noelia perooo...¿dónde está el vídeo que muestra cómo se hace?

**Comment by noeliagmez3** [comment]
Ya está terminada la tarea #48 
https://drive.google.com/file/d/0B3_UAgSTOs3nYWlVREtVNFNTVTA/view?usp=sharing

**Comment by noeliagmez3** [comment]
Ya está terminada la tarea
Aquí tienes [el video](https://drive.google.com/open?id=0BxqNTWA5v2JTWWdCeS1RQUFLQ2c)

**Comment by profeIAP** [comment]
Cachis... está muy bien el vídeo pero ¿no te ha llamado la atención que el tercer método utilizado para poner una imagen no funciona correctamente.

Si lo necesitas (en el vídeo se ve cómo es porque aparece automáticamente cuando has ido seleccionando imágenes) te cuento cuál es la sintaxis para añadir una imagen usando MarkDown

**Comment by noeliagmez3** [comment]
Vale, el proximo dia lo modifico, gracias.

El 9/1/2017 14:55, "Profesor IAP" <notifications@github.com> escribió:

Cachis... está muy bien el vídeo pero ¿no te ha llamado la atención que el
tercer método utilizado para poner una imagen no funciona correctamente.

Si lo necesitas (en el vídeo se ve cómo es porque aparece automáticamente
cuando has ido seleccionando imágenes) te cuento cuál es la sintaxis para
añadir una imagen usando MarkDown

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/profeIAP/Documentacion/issues/48#issuecomment-271289812>,
or mute the thread

**Comment by noeliagmez3** [comment]
![tree1](https://cloud.githubusercontent.com/assets/24393386/21883341/e30f1efc-d8ae-11e6-9e99-bf8ade1f513b.png)
![tree1](https://cloud.githubusercontent.com/assets/24393386/21883342/e803b206-d8ae-11e6-969a-b8df359c6dcf.png)
![aquí se ve un arbol muy bonito](https://pngscreativos.files.wordpress.com/2016/03/tree1.png)

**Comment by noeliagmez3** [comment]
Ya te he cambiado [el vídeo](https://drive.google.com/open?id=0BxqNTWA5v2JTTHRkbDdCNW1VZUU)

**Comment by profeIAP** [comment]
Perfecto Noelia, muy buen trabajo.
Gracias
