### ISSUE TITLE
Narrar cómo cerrar sesión en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/Documentacion#58]
Describir el proceso seguido en el vídeo de la tarea #57

**Comment by elenashp** [comment]
le asigno esto a sofialg mientras espera que le acepten entrar en su cuenta

**Comment by profeIAP** [comment]
¡Qué jaleo habéis montado quitando y poniendo asignaciones en esta tarea!

Insisto: la próxima vez que veáis que alguien tiene la tarea ni os molestéis en poneros vosotros.

Por zanjar el tema: ¿alguno de los "afectados" siente "vulnerados" sus derechos con tanta asignación?

**Comment by juankagb00** [comment]
Maestro que fué un fallo tecnico creo que le dí sin querer además yo estoy
haciendo ya la tarea de narrar como soltar una tarea en Git Hub.

El 12 ene. 2017 18:09, "Profesor IAP" <notifications@github.com> escribió:

¡Qué jaleo habéis montado quitando y poniendo asignaciones en esta tarea!

Insisto: la próxima vez que veáis que alguien tiene la tarea ni os
molestéis en poneros vosotros.

Por zanjar el tema: ¿alguno de los "afectados" siente "vulnerados" sus
derechos con tanta asignación?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/profeIAP/Documentacion/issues/58#issuecomment-272222245>,
or mute the thread

**Comment by profeIAP** [comment]
Perfecto, gracias por aclararlo @juankagb00 

En principio la tarea la tiene asignada @noeliagmez3, ya nos contará ella si es correcto 😏

**Comment by juankagb00** [comment]
Vale, pero creo que le dí sin querer y no me daría cuenta.

**Comment by noeliagmez3** [comment]
Si, yo he cogido esa tarea y estoy trabajando en ella.

**Comment by profeIAP** [comment]
Genial, aclarado queda. 
Gracias Noelia

**Comment by noeliagmez3** [comment]
Aquí tienes[ el audio](https://drive.google.com/open?id=0B3_UAgSTOs3ncFQ1MnN1blpKOUE) de esta tarea.

**Comment by profeIAP** [comment]
@noeliagmez3, si no hay vídeo en la tarea #57 ¿cómo lo has podido "narrar"?
¿Habrá eliminado alguien el enlace al vídeo?

**Comment by noeliagmez3** [comment]
El video lo grabó Carlos José y en la carpeta de multimedia está su video.

**Comment by profeIAP** [comment]
Por fin [lo enlazó](https://github.com/profeIAP/Documentacion/issues/57#issuecomment-273714663)

Ahora me surje una duda @noeliagmez3: ¿no viste que ya estaba narrado por @Carjop? 😳

**Comment by noeliagmez3** [comment]
Cuando yo me asigne la tarea estaba abierta

**Comment by noeliagmez3** [comment]
Incluso el video no estaba grabado

**Comment by profeIAP** [comment]
Estos últimos comentarios han debido "cruzarse" con los míos porque carecen de sentido... XD

**Comment by noeliagmez3** [comment]
Maestro ya está todo aclarado con Carlos José, corrige mi audio :(

**Comment by profeIAP** [comment]
Corregido ha quedado... confío "ciegamente" que no me encontraré a Carlos por los pasillos con muletas y/o algún ojo morado 😒
